# Generated by Django 4.2.30 on 2026-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='category',
            field=models.CharField(blank=True, help_text='z.B. Restaurant, Arzt, Handwerker', max_length=200),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='inquiry_url',
            field=models.URLField(blank=True, help_text='Link zum Kontakt-/Anfrageformular'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_area',
            field=models.CharField(blank=True, help_text='z.B. Berlin, Brandenburg, deutschlandweit', max_length=500),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='special_hours',
            field=models.TextField(blank=True, help_text='Feiertage, Sonderzeiten'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Mo-Fr: 9-18 Uhr, Sa: 10-14 Uhr'),
        ),
    ]
