# Generated by Django 4.2.30 on 2026-06-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0002_businessprofile_category_businessprofile_inquiry_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='tags',
            field=models.CharField(blank=True, help_text='Kommagetrennt: handwerk, notdienst, 24h', max_length=500),
        ),
    ]
