# Generated by Django 4.2.30 on 2026-06-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('category', models.CharField(default='Web', max_length=100)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-indexed_at'],
            },
        ),
    ]
