# Generated by Django 4.2.30 on 2026-06-15 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0002_searchquery_adcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('status_code', models.IntegerField(null=True)),
                ('pages_indexed', models.IntegerField(default=0)),
                ('pages_queued', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('priority', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Wartend'), ('crawling', 'In Arbeit'), ('done', 'Erledigt'), ('failed', 'Fehler')], db_index=True, default='pending', max_length=10)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=253)),
                ('depth', models.IntegerField(default=0)),
                ('retries', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('method', models.CharField(choices=[('dns', 'DNS TXT Record'), ('meta', 'Meta-Tag'), ('file', 'HTML-Datei')], default='dns', max_length=10)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('verified', 'Verifiziert'), ('rejected', 'Abgelehnt')], default='pending', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='searchindex',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=253),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='page_rank',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['domain'], name='search_sear_domain_78e487_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['category'], name='search_sear_categor_dc6fcb_idx'),
        ),
        migrations.AddField(
            model_name='domainverification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_domains', to=settings.AUTH_USER_MODEL),
        ),
    ]
