# Generated by Django 4.2.30 on 2026-06-15 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0003_crawllog_crawlqueue_domainverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='cost_per_click',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=6),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
