# Generated by Django 4.2.30 on 2026-06-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_adcampaign_cost_per_click_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcampaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='cost_per_click',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
